server:
  port: 10000
spring:
  application:
    name: controller
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
