server:
  port: 8761
spring:
  application:
    name: service-eureka-server
eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


